### PR TITLE
Fixed failing tests.

### PR DESCRIPTION
**Pull request by theseion**
There were a couple of issues with field due to the move to UFFI which I fixed.
In addition there was a double free issue on LGitTreeEntry.

### CODE REVIEW

**Comment by tinchodias** [comment]
I got a loading error, possibly because I used libgit while loading libgit :).
I mean, I did checkout the PR branch, then added the repository to Iceberg, then clicked on packages and finally select "reload".

Was there another way to do it?

**Comment by theseion** [comment]
Uh yeah, there might be issues with that. I'll have to look at it again to see what can be done about it.

**Comment by tinchodias** [comment]
Do you know what's a good alternative to load Libgit without using it?

**Comment by theseion** [comment]
No, I don't. Maybe @guillep or @tesonep do, as they probably have to have some bootstrapping code for it.

**Comment by tinchodias** [comment]
I plan to see Pablo in 2 weeks and can push this.

**Comment by theseion** [comment]
This is not a the perfect solution but at least it works:
```
Iceberg enableMetacelloIntegration: false.
Smalltalk packages
	select: [ :package | package packageName beginsWith: 'LibGit' ]
	thenDo: [ :package | package removeFromSystem ].
Metacello new
	baseline: 'LibGit';
	repository: 'filetree:///<path to repos>/libgit2-pharo-bindings';
	ignoreImage;
	load.
Iceberg enableMetacelloIntegration: true.
```

**Comment by tinchodias** [comment]
Great Max, I can try it this week.
Do you know how is the merging of PRs in this project related to [this recent issue](https://github.com/pharo-project/pharo/issues/5129) in Pharo project? (it mentions a Libgit postload action)

**Comment by theseion** [comment]
Great!. Not in detail but it appears that `FFICompilerPlugin` needs to be reinitialized to correctly track the pragmas in the FFI methods. For this PR that won't matter as we don't yet have those pragmas in place. Once we merge it though, we'll have to update the baseline.

**Comment by tinchodias** [comment]
I think it's ready to merge: I've just downloaded a Pharo8 64 bits, loaded and ran every test in LibGit-Tests and got green results.

Only one small fix to your loading script, Max: load development group.

~~~


Iceberg enableMetacelloIntegration: false.
Smalltalk packages
	select: [ :package | package packageName beginsWith: 'LibGit' ]
	thenDo: [ :package | package removeFromSystem ].
Metacello new
	baseline: 'LibGit';
	repository: 'filetree:////Users/tinchodias/d/iceberg-shared-repositories/pharo-vcs/libgit2-pharo-bindings';
	ignoreImage;
	load: #(development).
Iceberg enableMetacelloIntegration: true.
~~~

**Comment by tinchodias** [comment]
What's missing to merge it? I don't have permissions. Do you think it's ready to be merged, @guillep ?

**Comment by theseion** [comment]
Thanks Martin.

**Pull request merged**
