### PR TITLE
Remove call to deprecated Author

### PR DESCRIPTION
**Pull request by jecisc**
Author will be removed so I'm removing the call to it

### CODE REVIEW

**Comment by Ducasse** [comment]
OK I wanted to rekick the build but I cannot.

**Comment by Ducasse** [comment]
I cannot integrate so I won't.

**Comment by jecisc** [comment]
> I cannot integrate so I won't.

This is weird because your are the owner of pharo-vcs organization.

I'll merge it since you were about to do it and I now have a green CI after my last fixes

**Comment by Ducasse** [comment]
Christophe added me to the project

**Pull request merged**
